const CFG = {
  TIMEZONE: "Europe/Madrid",
  SECRET_KEY: "grefa2026",

  SHEETS: {
    FLOTA: "FLOTA",
    USUARIOS: "USUARIOS",
    SOLICITUDES: "SOLICITUDES",
    USO: "USO",
    LIBERACIONES: "LIBERACIONES",
    MANTENIMIENTOS: "MANTENIMIENTOS",
    GASTOS: "GASTOS",
    VENCIMIENTOS: "VENCIMIENTOS",
    CAT_TIPOS_GASTO: "CAT_TIPOS_GASTO",
    CAT_TIPOS_MANTENIMIENTO: "CAT_TIPOS_MANTENIMIENTO",
    LOG_API: "LOG_API"
  },

  ESTADOS: {
    SOLICITUD_PENDIENTE: "PENDIENTE",
    SOLICITUD_APROBADA: "APROBADA",
    SOLICITUD_RECHAZADA: "RECHAZADA",
    SOLICITUD_CANCELADA: "CANCELADA",
    SOLICITUD_LIBERADA: "LIBERADA"
  }
};